# @references(level=0):
# - .windsurfrules
# - CODE_OF_CONDUCT.md
# - MQP.md
# - ROADMAP.md
# - CROSSREF_STANDARD.md

name: X Daily Post

on:
  workflow_dispatch:
  schedule:
    - cron: '45 23 * * *'  # 23:45 UTC daily (~end of day for most zones)

jobs:
  post-daily-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tweepy
        run: pip install tweepy

      - name: Compose tweet text
        id: compose
        run: |
          # Use simple placeholder for public repository
          echo "text=Daily update from the EGOS project. Check out our latest developments at https://github.com/enioxt/EGOSystem #EGOS #OpenSource" >> $GITHUB_OUTPUT

      - name: Post to X
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
        run: |
          python scripts/utils/post_to_x.py --text "${{ steps.compose.outputs.text }}"