# @references(level=0):
# - .windsurfrules
# - CODE_OF_CONDUCT.md
# - MQP.md
# - ROADMAP.md
# - CROSSREF_STANDARD.md

name: X Daily Post

on:
  workflow_dispatch:
    inputs:
      summary:
        description: "Short summary (optional)"
        required: false
      keyword:
        description: "Additional hashtag (without #, will be converted to UPPERCASE)"
        required: false
  schedule:
    - cron: '45 23 * * *'  # 23:45 UTC daily (~end of day for most zones)

jobs:
  post-daily-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests requests-oauthlib

      - name: Post to X
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_OAUTH2_ACCESS_TOKEN: ${{ secrets.X_OAUTH2_ACCESS_TOKEN }}
          X_OAUTH2_REFRESH_TOKEN: ${{ secrets.X_OAUTH2_REFRESH_TOKEN }}
        run: |
          SUMMARY="${{ github.event.inputs.summary }}"
          KEYWORD="${{ github.event.inputs.keyword }}"
          if [ -z "$SUMMARY" ]; then SUMMARY="Daily project update."; fi
          if [ -z "$KEYWORD" ]; then KEYWORD="DAILY"; fi
          REPORT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          python -m scripts.utils.post_to_x --summary "$SUMMARY" --keyword "$KEYWORD" --report-url "$REPORT_URL"